import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Groovy!</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to{' '}
                    <a
                        href='https://www.udemy.com/course/modern-react-bootcamp/'
                        target='blank'
                        rel='noreferrer'
                    >
                        Groovy!
                    </a>
                </h1>

                <p className={styles.description}>
                    Choose an <code className={styles.code}>app</code> below to
                    get started.
                </p>

                <div className={styles.grid}>
                    <Link href='/color-boxes'>
                        <a className={styles.card}>
                            <h2>Color Boxes &rarr;</h2>
                            <p>
                                Random colors are on your way.{' '}
                                <small>(Section 9: State Exercises)</small>
                            </p>
                        </a>
                    </Link>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href='https://github.com/kleandra-v8/modern-react-colt-steele'
                    target='_blank'
                    rel='noopener noreferrer'
                >
                    August 2021 &nbsp; &#x2055; &nbsp; Karla Vargas
                </a>
            </footer>
        </div>
    );
}
